M48
; DRILL file {KiCad 9.0.7} date 2026-02-23T18:09:31-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-23T18:09:31-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X102.0Y-101.25
X123.0Y-50.25
X170.75Y-50.25
X170.75Y-101.25
M30
